
add_additional_payment:
  description: Add extra payment to mortgage
  fields:
    amount:
      description: Amount in GBP
      example: 500
      required: true
    date:
      description: Date of payment (YYYY-MM-DD)
      example: "2025-07-01"
      required: false


set_interest_rate:
  description: "Change the mortgage interest rate"
  fields:
    rate:
      description: "New interest rate in %"
      example: 3.5
